### ISSUE TITLE
BUG: New bug discovered

### ISSUE THREAD

**Issue by luke-hagar-sp** [sailpoint-oss/golang-sdk#10]
![image](https://user-images.githubusercontent.com/98849695/219690262-1648a4f0-2d62-40e2-854d-973d86bfbc34.png)

**Comment by colin-mckibben-sp** [comment]
Please describe the genus/species of this bug.  It's not clear from this image what we are dealing with.

**Comment by luke-hagar-sp** [comment]
```
Scientific name: Boisea trivittata
Family: Rhopalidae
Kingdom: Animalia
Order: Hemiptera
Phylum: Arthropoda
```

**Comment by colin-mckibben-sp** [comment]
This is a box elder bug.  Please see this article for more information about the bug: https://en.wikipedia.org/wiki/Boxelder_bug.  This bug shouldn't be a problem in production, but if you are experiencing issues I highly recommend you reach out to ES (exterminator services) to have them take care of the issue.

**Comment by luke-hagar-sp** [comment]
That solves my issue! Thank you.
