### ISSUE TITLE
Provide abstraction to make handling pagination easier

### ISSUE THREAD

**Issue by wcarson** [sailpoint-oss/golang-sdk#2]
This is an enhancement request to add some type of abstraction over results pagination to remove the burden on developers to manually do it (e.g. calculate offsets, keep track of total results, build new new requests per page, etc.)

Some examples of how other Go SDKs have implemented this:
- [Okta Golang SDK](https://github.com/okta/okta-sdk-golang#pagination)
- [AWS SDK for Go V2](https://aws.github.io/aws-sdk-go-v2/docs/making-requests/#using-paginators)
- [Azure SDK for Go](https://learn.microsoft.com/en-us/azure/developer/go/azure-sdk-core-concepts#pagination-methods-that-return-collections)

**Comment by philip-ellis-sp** [comment]
added a generic class to allow for pagination and added examples for doing such in the readme
