### ISSUE TITLE
CC Apps OpenAPI spec uses invalid placeholder format for ID path param

### ISSUE THREAD

**Issue by wcarson** [sailpoint-oss/golang-sdk#23]
The CC Apps API Open API spec uses an incorrect placeholder format for path parameters which causes requests requiring a path parameter to fail. The code is trying to replace `{id}` with the provided app ID, however, the path template has `:id` as the placeholder.

**Spec**
https://github.com/sailpoint-oss/golang-sdk/blob/0354e8d5fecaae25b7204629823db8cced251c55/cc/api/openapi.yaml#L69-L71

**Generated code**
https://github.com/sailpoint-oss/golang-sdk/blob/0354e8d5fecaae25b7204629823db8cced251c55/cc/api_applications.go#L248-L249

**Comment by tyler-mairose-sp** [comment]
This is fixed in https://github.com/sailpoint-oss/golang-sdk/commit/814d141b78156f1a0eea2cba31a40f63f5b01179
