### ISSUE TITLE
Beta Get Identity method has incorrect path ID replacement

### ISSUE THREAD

**Issue by wcarson** [sailpoint-oss/golang-sdk#27]
The beta GetIdentity method incorrectly replaces the ID path parameter resulting in "identity not found" for any request.

https://github.com/sailpoint-oss/golang-sdk/blob/814d141b78156f1a0eea2cba31a40f63f5b01179/beta/api_identities.go#L225-L226

Line 226 should replace "{id}", not "{identityId}"

**Comment by tyler-mairose-sp** [comment]
This is fixed in https://github.com/sailpoint-oss/golang-sdk/commit/2f6c956cb8b9cfc13634c55d63a503951f673669 and released in https://github.com/sailpoint-oss/golang-sdk/releases/tag/v1.0.3
