### ISSUE TITLE
CC Apps API should return typed results instead of http.Response

### ISSUE THREAD

**Issue by wcarson** [sailpoint-oss/golang-sdk#28]
The CC Apps API "Get App", "List Apps" method only returns the raw http.Response and not an Application object. This requires consumers to create their own Application structs and unmarshal the raw JSON response.

**Comment by tyler-mairose-sp** [comment]
This is fixed in https://github.com/sailpoint-oss/golang-sdk/commit/2f6c956cb8b9cfc13634c55d63a503951f673669 and released in https://github.com/sailpoint-oss/golang-sdk/releases/tag/v1.0.3
