### ISSUE TITLE
Add V2 or CC Identities API to SDK

### ISSUE THREAD

**Issue by wcarson** [sailpoint-oss/golang-sdk#29]
There is currently no way to find/get an Identity by legacy (numeric) ID. This is required for endpoints like /cc/apps which return owner information using the legacy ID (see "owner" attribute below from `/cc/apps/:id` response).

```json
{
  "id": "24238",
  "appId": "1198",
  ...
  "owner": {
    "id": "378284",
    "name": "Wayne Carson Admin"
  },
  ...
}
```

**Comment by tyler-mairose-sp** [comment]
This is fixed in https://github.com/sailpoint-oss/golang-sdk/commit/2f6c956cb8b9cfc13634c55d63a503951f673669 and released in https://github.com/sailpoint-oss/golang-sdk/releases/tag/v1.0.3
