### ISSUE TITLE
Incorrect data type for AccessProfileIds on CC Application struct?

### ISSUE THREAD

**Issue by wcarson** [sailpoint-oss/golang-sdk#31]
I think this should be a []string (array of Access Profile IDs) and not a map based on looking at how the UI uses this attribute.

https://github.com/sailpoint-oss/golang-sdk/blob/01aa6cf04ff7872a2ed9e64a9396d88bd1fb7003/cc/model_list_applications_200_response_inner.go#L71

**Comment by tyler-mairose-sp** [comment]
Hey @wcarson,

Thanks for bringing this to our attention! In looking into this I wasn't able to get any values back in the accessProfileIds on the Application struct when calling `/cc/api/app/get/:id`, even though the app has access profiles associated with it.

Could you provide an example of what is returned with your app?

I can fix this, but in our testing the accessProfileIds field is always `null`.

**Comment by wcarson** [comment]
Hi @tyler-mairose-sp,
The API won't return the AP IDs back with the normal get app method, or at least I don't know of a way to get it to return them. There's an API specifically for getting the list of APs associated with an app: `/cc/api/app/getAccessProfiles/:id`. As far as I can tell, the `accessProfileIds` attribute is used for _updates_. If you look at dev tools when you add/remove an AP from an app the UI posts an object like `{ accessProfileIds: ["id1", "id2"] }`.

**Comment by tyler-mairose-sp** [comment]
Hey @wcarson,

Coming back through the Github issues here and getting them sorted out. This one is fixed with this commit  https://github.com/sailpoint-oss/golang-sdk/commit/65576bf11bd414d399c4993dd74e7103e95f58ee and will be released with the next version early next week.
