### ISSUE TITLE
JsonPatchOperation documentation help

### ISSUE THREAD

**Issue by Flo451** [sailpoint-oss/golang-sdk#48]
Hi, 

I was looking at the documentation for PATCH operations but am having some troubles with the examples.

Fore example here it suggests that the Description Path will be replaced but it doesn't specify a value it will be replaced with i.e. old description vs. new description. Are those valid examples? 

In any case I would appreciate if you could give an example of how to actually use this method. 

`jsonPatchOperation := []openapiclient.JsonPatchOperation{*openapiclient.NewJsonPatchOperation("replace", "/description")}`

https://github.com/sailpoint-oss/golang-sdk/blob/55c034cf0c78b6a03f55be98e668c1620164e2c5/v3/docs/AccessProfilesAPI.md#PatchAccessProfile

**Comment by tyler-mairose-sp** [comment]
Hey @Flo451,

Our documentation generated is not the best right now, it is actually something we are actively working on. We do have an example here https://developer.sailpoint.com/idn/tools/sdk/go/update that shows how to pass the value into the patch operation.

The specific lines are below:
```go
 updatedDescription := `This is an updated description for the workgroup.`
 newDescriptionValue := beta.JsonPatchOperationValue{String: &updatedDescription}
 patchArray := []beta.JsonPatchOperation{{Op: "replace", Path: "/description", Value: &newDescriptionValue}}

```
