### ISSUE TITLE
Deserialization problem with Beta.AccessRequestsAPI.ListAccessRequestStatus

### ISSUE THREAD

**Issue by wcarson** [sailpoint-oss/golang-sdk#61]
It looks like there may be a problem deserializing the results from `Beta.AccessRequestsAPI.ListAccessRequestStatus`. The following code produces the expected number of results, but all of the objects are empty/default values.

```go
result, res, err := api.Beta.AccessRequestsAPI.ListAccessRequestStatus(context.Background()).Limit(10).Execute()
```

**Result**
![CleanShot 2024-03-14 at 08 36 27](https://github.com/sailpoint-oss/golang-sdk/assets/963939/84bec6f0-f158-4ec3-a481-0363b59e5371)

**Comment by tyler-mairose-sp** [comment]
Hey @wcarson,

This has to do with the same timestamp issue and is fixed in https://github.com/sailpoint-oss/golang-sdk/commit/669e9bcbd062d8ce934d8b085146e9e08e24ec17

This will be a part of the next release.
