### ISSUE TITLE
Timestamp Parsing Errors in new Apps API

### ISSUE THREAD

**Issue by wcarson** [sailpoint-oss/golang-sdk#73]
It appears that the created/modified timestamp format being returned by the new Apps API is inconsistent as shown below:

```jsonc
{
  //full response omitted for brevity
  "id": "47a52fb846364c89afe86257973d080a",
  "name": "My Sample App",
  "created": "2024-05-02T15:01:54.809Z",
  "modified": "2024-05-02T15:05Z" //missing seconds and millis
}
```

This is causing errors in the `GetSourceApp` and `ListAllSourceApp` methods:
```
parsing time "2024-05-02T15:05Z" as "2006-01-02T15:04:05Z07:00": cannot parse "Z" as ":"
```

**Comment by wcarson** [comment]
A potential workaround is to find all apps with a non-standard `modified` timestamp, make any change and save. This will force the timestamp to the correct format. Not ideal, but workable.

**Comment by wcarson** [comment]
Looks like a similar issue may have been patched for Governance Groups. Can this be extended to Apps?

https://github.com/sailpoint-oss/golang-sdk/blob/de0ade20481317df4100a13ff7ae3e218218fede/sdk-resources/postscript.js#L182

**Comment by tyler-mairose-sp** [comment]
Hello @wcarson,

This has been fixed in https://github.com/sailpoint-oss/golang-sdk/commit/669e9bcbd062d8ce934d8b085146e9e08e24ec17 and will be a part of the next release.
