### ISSUE TITLE
Beta Governance Group Add Members fails due to type mismatch between API response and SDK

### ISSUE THREAD

**Issue by wcarson** [sailpoint-oss/golang-sdk#75]
Using the `Beta.GovernanceGroupsAPI.UpdateWorkgroupMembers` method to bulk add members to a Governance Group fails with the following error:

```
json: cannot unmarshal number into Go struct field  _WorkgroupMemberAddItem.status of type string
```

This looks like it's occurring because there's a mismatch on the type of the `status` attribute of the response.

API JSON Response
```jsonc
[
    {
        "id": "2c9180848051e172018052395b8827ff",
        "description": "Identity is added into Governance Group members list.",
        "status": 201 // <-- number
    }
]
```

SDK type
```go
type WorkgroupMemberAddItem struct {
	Id string `json:"id"`
	Status string `json:"status"` // <-- string
	Description *string `json:"description,omitempty"`
	AdditionalProperties map[string]interface{}
}
```

**Comment by jtharbison** [comment]
I have this issue too and it occurs on removing members too.

**Comment by tyler-mairose-sp** [comment]
This is fixed for both update and delete with https://github.com/sailpoint-oss/golang-sdk/commit/66d40333628e3d79e661ff25110eb4ad1008b082 and will be in the next release.
