### ISSUE TITLE
Could not read Workflow '(workflow name)': data failed to match schemas in anyOf(WorkflowTriggerAttributes)

### ISSUE THREAD

**Issue by sr-rom** [sailpoint-oss/golang-sdk#80]
When a Workflow has an EVENT trigger configured using the Basic tab, it populates a trigger attribute called "attributeToFilter", which IDN uses to compose the "Filter" attribute we can see in the Advanced tab. If we retrieve the Workflow using the API, we can see these attributes:

        "trigger": {
            "type": "EVENT",
            "attributes": {
                "filter.$": "$.changes[?(@.attribute== \"cloudLifecycleState\")]",
                "id": "idn:identity-attributes-changed",
                "attributeToFilter": "cloudLifecycleState",
            }
        }

This configuration of the Workflow can't be read by the SDK, as the "attributeToFilter" is not anywhere in the SDK, throwing this error:
Could not read Workflow '(workflow name)': data failed to match schemas in anyOf(WorkflowTriggerAttributes)

The only workaround we've found is to remove the "attributeToFilter" attribute using a manual PATCH call to the API, and then we can read and modify the workflow normally.

Is there a way to make the SDK to be able to handle workflows with the "attributeToFilter" attribute in the trigger atributes?

**Comment by tyler-mairose-sp** [comment]
Hey @sr-rom,

Can you try it on https://github.com/sailpoint-oss/golang-sdk/releases/tag/v2.1.17, this should be fixed. If you still have issues please re-open!
